services:

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: MovieMatch1234
      POSTGRES_DB: MovieMatch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    restart: unless-stopped
    ports:
      - "8085:8085"
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8085 --project=my-local-project


  backend:
    image: movie-match:backend-v1.1
    container_name: movie-match-backend
    restart: unless-stopped
    ports:
      - "5000:8081"
    environment:
      PORT: 8081

      DATABASE_URL: postgresql+psycopg://myuser:MovieMatch1234@db:5432/MovieMatch
      
      REDIS_HOST: redis
      REDIS_PORT: 6379

      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_BASE_URL: https://api.themoviedb.org/3
      TMDB_IMAGE_BASE_URL: https://image.tmdb.org/t/p
      TMDB_IMAGE_SIZE: w500

      SECRET_KEY: dev-secret
      SESSION_HEADER: X-Session-ID
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000

      GCP_PROJECT_ID: my-local-project
      TOPIC_ID: events
      PUBSUB_EMULATOR_HOST: pubsub-emulator:8085
    depends_on:
      - db
      - redis
      - pubsub-emulator


volumes:
  redis_data:
  postgres_data: