services:

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: MovieMatch1234
      POSTGRES_DB: MovieMatch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: Uncomment the line below to run initialization scripts on first boot
      # - ./init-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data: