name: Next.js CI/CD Pipeline

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch: # Enables the "Run workflow" button in the GitHub UI

# Applies to the entire workflow
defaults:
  run:
    working-directory: ./frontend  # Set the working directory to the frontend folder for all steps

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Fetch code from your repository
    - name: Checkout repository
      uses: actions/checkout@v7

    # Step 2: Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 24
        cache: 'npm'       # Automatically caches global npm dependencies

    # Step 3: Install clean dependencies
    - name: Install Dependencies
      run: npm ci

    # Step 4: Build the application
    - name: Build Project
      run: npm run build